"""
audit/schema.py

JSON Schema (Draft 2020-12) for RGP audit reports.

Five structural sections covering the complete scientific audit trail:

  1. provenance           Immutable foundation: exact git commit hash,
                           SeedRegistry master seed, and DataAuditor-generated
                           SHA-256 checksums for every input dataset.

  2. orchestration        Temporal and DAG execution logs at nanosecond
                           resolution, plus interrupt/recovery event log for
                           checkpoint-based restarts.

  3. math_telemetry       High-resolution mathematical measurements:
                           full layer-wise SVD spectra (not just mean), Lyapunov
                           spectrum evolution across training, Fisher metric
                           condition number and rank stability, and RG operator
                           information flow coefficients.

  4. hardware_forensics   Dynamic hardware measurements: per-layer VRAM
                           byte-count allocation log and per-kernel compute
                           latency records for O(N) scaling verification.

  5. integrity            Cryptographic seal: SHA-256 hash-chain linking
                           every section to all preceding sections, optional
                           digital signature over the chain tip, and a
                           file-level manifest for repository state.

Usage
-----
    from audit.schema import AuditSchema
    AuditSchema.validate(report)                      # raises on invalid
    ok, errors = AuditSchema.validate_soft(report)    # (bool, list[str])
    print(AuditSchema.as_json())                      # pretty schema dump
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Tuple

# ---------------------------------------------------------------------------
# $defs  reusable sub-definitions
# ---------------------------------------------------------------------------

_DEFS: Dict[str, Any] = {

    # ------------------------------------------------------------------ #
    # Section 1  data identity                                           #
    # ------------------------------------------------------------------ #

    "data_identity": {
        "type": "object",
        "description": (
            "SHA-256 checksum of one dataset or input file, generated by "
            "DataAuditor.compute_checksum() before training begins.  "
            "Embedding this in the report makes the exact input bytes "
            "uniquely identifiable and verifiable by any external reviewer."
        ),
        "required": ["dataset_name", "sha256", "verified"],
        "properties": {
            "dataset_name": {
                "type": "string",
                "description": "Logical name of the dataset (e.g. 'synthetic_hierarchy_n10000').",
            },
            "path": {
                "type": ["string", "null"],
                "description": "Absolute or repo-relative filesystem path.",
            },
            "sha256": {
                "type": "string",
                "description": "SHA-256 hex digest of the dataset directory tree or file.",
                "pattern": "^[0-9a-f]{64}$",
            },
            "size_bytes": {
                "type": ["integer", "null"],
                "description": "Total byte size of the dataset.",
            },
            "generation_seed": {
                "type": ["integer", "null"],
                "description": "Master seed used to generate this dataset, if synthetic.",
            },
            "verified": {
                "type": "boolean",
                "description": "True when DataAuditor.verify_checksum() confirmed the hash matched.",
            },
            "verified_at_ns": {
                "type": ["integer", "null"],
                "description": "Monotonic nanosecond timestamp of the verification call.",
            },
        },
    },

    # ------------------------------------------------------------------ #
    # Section 2  DAG node and checkpoint event                          #
    # ------------------------------------------------------------------ #

    "dag_node": {
        "type": "object",
        "description": (
            "A single node in the workflow DAG.  Every major execution unit  "
            "suite, script, training phase, RG transformation pass, data checksum "
            "verification  emits one node record with nanosecond-resolution "
            "start and end timestamps.  parent_node_id enables full DAG reconstruction."
        ),
        "required": ["node_id", "node_type", "started_ns", "ended_ns", "status"],
        "properties": {
            "node_id": {
                "type": "string",
                "description": "UUID v4 uniquely identifying this node within the run.",
            },
            "parent_node_id": {
                "type": ["string", "null"],
                "description": "node_id of the parent node (null for root nodes).",
            },
            "node_type": {
                "type": "string",
                "enum": [
                    "run_root",
                    "pytest_suite",
                    "pytest_case",
                    "study_script",
                    "training_phase",
                    "rg_transformation",
                    "forward_pass",
                    "backward_pass",
                    "checkpoint_save",
                    "checkpoint_load",
                    "data_checksum",
                    "figure_generation",
                ],
            },
            "label": {
                "type": "string",
                "description": "Human-readable label (e.g. 'tests/unit', 'H1 step 200 forward').",
            },
            "started_ns": {
                "type": "integer",
                "description": "time.monotonic_ns() at node start.",
            },
            "ended_ns": {
                "type": "integer",
                "description": "time.monotonic_ns() at node end.",
            },
            "duration_ns": {
                "type": "integer",
                "description": "ended_ns - started_ns, pre-computed for query convenience.",
            },
            "status": {
                "type": "string",
                "enum": ["running", "passed", "failed", "error", "skipped", "interrupted"],
            },
            "metadata": {
                "type": "object",
                "description": "Arbitrary key-value pairs specific to this node type.",
                "additionalProperties": True,
            },
        },
    },

    "checkpoint_event": {
        "type": "object",
        "description": (
            "Records a training interruption or checkpoint-based recovery.  "
            "Every resume populates this record so the temporal audit trail is "
            "unbroken even across multi-day runs with restarts."
        ),
        "required": ["event_type", "timestamp_ns", "checkpoint_path"],
        "properties": {
            "event_type": {
                "type": "string",
                "enum": ["save", "interrupt", "resume"],
            },
            "timestamp_ns": {
                "type": "integer",
                "description": "Monotonic nanosecond timestamp of the event.",
            },
            "checkpoint_path": {
                "type": "string",
                "description": "Repo-relative or absolute path to the checkpoint file.",
            },
            "checkpoint_sha256": {
                "type": ["string", "null"],
                "description": "SHA-256 of the checkpoint file at save/load time.",
            },
            "step_at_event": {
                "type": "integer",
                "description": "Training step at the time of the event.",
            },
            "epoch_at_event": {
                "type": ["integer", "null"],
            },
            "reason": {
                "type": ["string", "null"],
                "description": "Human-readable reason for interruption (e.g. 'OOM', 'SIGTERM', 'time limit').",
            },
            "seed_state_embedded": {
                "type": "boolean",
                "description": "True if the full SeedRegistry RNG state is embedded in the checkpoint.",
            },
        },
    },

    # ------------------------------------------------------------------ #
    # Section 3  mathematical telemetry                                  #
    # ------------------------------------------------------------------ #

    "spectral_snapshot": {
        "type": "object",
        "description": (
            "Full singular value spectrum rho(lambda) of one layer's weight matrix "
            "at one training step.  The complete distribution is required  not just "
            "the mean  to enable Marchenko-Pastur fitting, Wigner semicircle "
            "verification, and Tracy-Widom edge detection in post-processing."
        ),
        "required": ["layer_idx", "step", "singular_values"],
        "properties": {
            "layer_idx":   {"type": "integer"},
            "layer_name":  {"type": ["string", "null"]},
            "step":        {"type": "integer"},
            "timestamp_ns":{"type": "integer"},
            "matrix_shape": {
                "type": "array",
                "items": {"type": "integer"},
                "minItems": 2,
                "maxItems": 2,
                "description": "[rows, cols] of the weight matrix.",
            },
            "singular_values": {
                "type": "array",
                "items": {"type": "number"},
                "description": (
                    "Complete sorted singular value array sigma_1 >= sigma_2 >= ... >= sigma_r.  "
                    "For matrices with r > 4096, store the top 512 and bottom 64 values "
                    "and set singular_values_truncated: true."
                ),
            },
            "singular_values_truncated": {
                "type": "boolean",
                "description": "True when only a subset of singular values is stored.",
            },
            "eigenvalue_density": {
                "type": "object",
                "description": "Histogram of lambda = sigma^2 for Marchenko-Pastur comparison.",
                "required": ["bin_edges", "counts"],
                "properties": {
                    "bin_edges": {
                        "type": "array",
                        "items": {"type": "number"},
                        "description": "n_bins + 1 bin-edge values.",
                    },
                    "counts": {
                        "type": "array",
                        "items": {"type": "integer"},
                        "description": "n_bins unnormalised count values.",
                    },
                    "n_bins": {"type": "integer"},
                },
            },
            "mp_fit": {
                "type": "object",
                "description": "Marchenko-Pastur distribution fit parameters.",
                "properties": {
                    "sigma_sq":     {"type": "number", "description": "Fitted sigma^2 (bulk variance)."},
                    "ratio_q":      {"type": "number", "description": "Aspect ratio q = p/n."},
                    "lambda_plus":  {"type": "number", "description": "Upper MP edge lambda+ = sigma^2(1+sqrt(q))^2."},
                    "lambda_minus": {"type": "number", "description": "Lower MP edge lambda- = sigma^2(1-sqrt(q))^2."},
                    "ks_statistic": {"type": "number", "description": "Kolmogorov-Smirnov statistic for goodness-of-fit."},
                    "ks_pvalue":    {"type": "number"},
                },
            },
            "distribution_class": {
                "type": "string",
                "enum": ["marchenko_pastur", "wigner_semicircle", "bulk_plus_outliers", "unknown"],
                "description": "Classifier output from the spectral analysis pipeline.",
            },
            "effective_rank": {
                "type": ["integer", "null"],
                "description": "Number of singular values above the MP upper edge lambda+.",
            },
        },
    },

    "lyapunov_snapshot": {
        "type": "object",
        "description": (
            "Lyapunov spectrum at one training step.  The complete spectrum "
            "lambda_1 >= lambda_2 >= ... >= lambda_n is required (not just the maximal "
            "exponent) because the Kaplan-Yorke dimension and regime classification "
            "depend on the sign pattern across the entire spectrum.  Computed via "
            "QR decomposition of the product Jacobian."
        ),
        "required": ["step", "spectrum"],
        "properties": {
            "step":        {"type": "integer"},
            "timestamp_ns":{"type": "integer"},
            "spectrum": {
                "type": "array",
                "items": {"type": "number"},
                "description": "Complete Lyapunov exponent spectrum in descending order.",
            },
            "max_lyapunov_exponent": {
                "type": "number",
                "description": "lambda_1  the leading Lyapunov exponent.",
            },
            "kaplan_yorke_dimension": {
                "type": ["number", "null"],
                "description": (
                    "D_KY = k + sum_{i=1}^{k} lambda_i / |lambda_{k+1}|, "
                    "where k is the largest index with sum_{i=1}^{k} lambda_i >= 0."
                ),
            },
            "sum_positive_exponents": {
                "type": "number",
                "description": "Sum of all positive exponents  measures information production rate.",
            },
            "regime": {
                "type": "string",
                "enum": ["ordered", "critical", "chaotic"],
                "description": (
                    "Dynamical regime: 'ordered' (lambda_1 < 0), "
                    "'critical' (lambda_1 ≈ 0), 'chaotic' (lambda_1 > 0)."
                ),
            },
            "qr_algorithm": {
                "type": "string",
                "enum": ["standard", "adaptive", "parallel"],
                "description": "QR algorithm variant from src/core/lyapunov.",
            },
            "n_steps_averaged": {
                "type": "integer",
                "description": "Number of Jacobian products averaged for this estimate.",
            },
        },
    },

    "fisher_snapshot": {
        "type": "object",
        "description": (
            "Fisher information metric geometry at one layer and step.  "
            "condition_number kappa = lambda_max / lambda_min is the key diagnostic "
            "for H1 validation.  effective_dimension drives the minimal-depth "
            "argument in H2.  rank_stability across steps validates training health."
        ),
        "required": ["layer_idx", "step", "condition_number", "rank"],
        "properties": {
            "layer_idx":        {"type": "integer"},
            "layer_name":       {"type": ["string", "null"]},
            "step":             {"type": "integer"},
            "timestamp_ns":     {"type": "integer"},
            "condition_number": {
                "type": "number",
                "description": "kappa(G^(k)) = lambda_max / lambda_min of the Fisher metric tensor.",
            },
            "lambda_max":       {"type": "number"},
            "lambda_min":       {"type": "number"},
            "clip_min": {
                "type": "number",
                "description": "Floor applied before computing kappa (FisherConditionTracker.clip_min).",
            },
            "rank": {
                "type": "integer",
                "description": "Numerical rank of G^(k) at tolerance 1e-10.",
            },
            "effective_dimension": {
                "type": ["number", "null"],
                "description": "d_eff = (tr G)^2 / tr(G^2), from FisherEffectiveDimension.",
            },
            "is_ill_conditioned": {
                "type": "boolean",
                "description": "True when kappa > warning_threshold (default 1e6).",
            },
            "eigenvalue_histogram": {
                "type": "object",
                "properties": {
                    "log_bin_edges": {"type": "array", "items": {"type": "number"}},
                    "counts":        {"type": "array", "items": {"type": "integer"}},
                },
            },
        },
    },

    "rg_operator_snapshot": {
        "type": "object",
        "description": (
            "Information flow coefficients for one RG operator at one step.  "
            "Quantifies how much information is integrated out (coarse-grained away) "
            "versus retained.  The cumulative_information_loss trajectory across depth "
            "is the primary mathematical evidence for the RG/depth correspondence (H1)."
        ),
        "required": ["layer_idx", "step", "operator_type"],
        "properties": {
            "layer_idx":    {"type": "integer"},
            "layer_name":   {"type": ["string", "null"]},
            "step":         {"type": "integer"},
            "timestamp_ns": {"type": "integer"},
            "operator_type": {
                "type": "string",
                "enum": ["standard", "residual", "attention", "wavelet", "learned"],
            },
            "coarse_graining_scale": {
                "type": "number",
                "description": (
                    "The length scale L at which coarse-graining operates.  "
                    "For wavelet operators: the wavelet scale index."
                ),
            },
            "information_retained_coefficient": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0,
                "description": (
                    "alpha_k = I(h^(k); h^(k-1)) / I(h^(0); h^(k-1)).  "
                    "Fraction of mutual information from the input surviving this step."
                ),
            },
            "information_integrated_out_coefficient": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0,
                "description": (
                    "beta_k = 1 - alpha_k.  The complementary fraction discarded "
                    "by this coarse-graining step."
                ),
            },
            "cumulative_information_loss": {
                "type": ["number", "null"],
                "description": "Running total sum_{i=1}^{k} beta_i up to this layer.",
            },
            "jacobian_singular_value_ratio": {
                "type": ["number", "null"],
                "description": (
                    "sigma_1 / sigma_r of the layer Jacobian dh^(k)/dh^(k-1).  "
                    "Ratio > 1: amplification; < 1: compression."
                ),
            },
            "correlation_decay_xi": {
                "type": ["number", "null"],
                "description": (
                    "Estimated correlation length xi(k) at this layer, "
                    "from the exponential decay fit xi(k) = xi_0 exp(-k/k_c)."
                ),
            },
        },
    },

    # ------------------------------------------------------------------ #
    # Section 4  hardware forensics                                      #
    # ------------------------------------------------------------------ #

    "vram_alloc_event": {
        "type": "object",
        "description": (
            "A single GPU memory allocation or deallocation event.  "
            "Plotting cumulative_bytes vs layer_idx yields the O(N) memory "
            "scaling curve that corroborates the complexity claim."
        ),
        "required": ["event", "bytes_delta", "cumulative_bytes", "timestamp_ns"],
        "properties": {
            "event": {
                "type": "string",
                "enum": ["alloc", "free", "peak"],
            },
            "layer_idx":        {"type": ["integer", "null"]},
            "layer_name":       {"type": ["string", "null"]},
            "tensor_shape": {
                "type": ["array", "null"],
                "items": {"type": "integer"},
                "description": "Shape of the tensor being allocated.",
            },
            "dtype": {
                "type": ["string", "null"],
                "description": "e.g. 'float16', 'float32', 'bfloat16'.",
            },
            "bytes_delta": {
                "type": "integer",
                "description": "Bytes added (positive) or freed (negative).",
            },
            "cumulative_bytes": {
                "type": "integer",
                "description": "Total bytes currently allocated after this event.",
            },
            "cumulative_gb": {
                "type": "number",
                "description": "cumulative_bytes / 1e9 for human readability.",
            },
            "timestamp_ns": {"type": "integer"},
        },
    },

    "kernel_latency_record": {
        "type": "object",
        "description": (
            "Compute latency for one GPU kernel execution, measured via "
            "torch.cuda.Event synchronisation.  Plotting duration_us vs "
            "problem_size_n across records validates the O(N) compute claim."
        ),
        "required": ["kernel_name", "duration_us", "device"],
        "properties": {
            "kernel_name": {
                "type": "string",
                "description": "CUDA kernel name or descriptive label (e.g. 'sgemm_N128_M256').",
            },
            "layer_idx":      {"type": ["integer", "null"]},
            "layer_name":     {"type": ["string", "null"]},
            "step":           {"type": ["integer", "null"]},
            "problem_size_n": {
                "type": ["integer", "null"],
                "description": "The N in the O(N) claim (neurons, tokens, or data points).",
            },
            "duration_us": {
                "type": "number",
                "description": "Kernel wall time in microseconds from CUDA Event timing.",
            },
            "device": {"type": "string"},
            "timestamp_ns": {"type": "integer"},
            "flops": {
                "type": ["number", "null"],
                "description": "Estimated FLOP count for this kernel.",
            },
            "throughput_gflops": {
                "type": ["number", "null"],
                "description": "flops / (duration_us * 1e-6) / 1e9.",
            },
        },
    },

    # ------------------------------------------------------------------ #
    # Section 5  cryptographic integrity                                 #
    # ------------------------------------------------------------------ #

    "block_hash_record": {
        "type": "object",
        "description": (
            "One link in the SHA-256 hash chain.  Each block's hash is computed "
            "over (block_name + block_content_json + previous_hash).  "
            "Modifying any value in any earlier block changes that block's sha256, "
            "which changes its chain_hash, which then does not match the next "
            "block's previous_hash  invalidating the entire chain tip."
        ),
        "required": [
            "block_index", "block_name",
            "block_sha256", "previous_hash", "chain_hash",
        ],
        "properties": {
            "block_index": {
                "type": "integer",
                "description": "Zero-based position in the chain.",
            },
            "block_name": {
                "type": "string",
                "description": "Logical name of the hashed section (e.g. 'provenance').",
            },
            "block_sha256": {
                "type": "string",
                "description": "SHA-256 hex digest of the JSON-serialised block content alone.",
                "pattern": "^[0-9a-f]{64}$",
            },
            "previous_hash": {
                "type": "string",
                "description": (
                    "chain_hash of the immediately preceding block.  "
                    "For the genesis block (block_index == 0) this is "
                    "the 64-character all-zero string."
                ),
                "pattern": "^[0-9a-f]{64}$",
            },
            "chain_hash": {
                "type": "string",
                "description": "SHA-256( previous_hash || block_sha256 ).  Stored as previous_hash by the next block.",
                "pattern": "^[0-9a-f]{64}$",
            },
        },
    },

    "digital_signature": {
        "type": "object",
        "description": (
            "Cryptographic signature over the chain tip hash, produced with the "
            "author's private key.  Verifiable with the corresponding public key "
            "to confirm the report originated from the author's authenticated machine."
        ),
        "required": ["algorithm", "signed_payload_sha256", "signature_hex"],
        "properties": {
            "algorithm": {
                "type": "string",
                "enum": ["Ed25519", "RSA-PSS-SHA256", "ECDSA-P256-SHA256"],
            },
            "public_key_fingerprint": {
                "type": ["string", "null"],
                "description": "SHA-256 fingerprint of the public key in colon-hex notation.",
            },
            "public_key_pem_path": {
                "type": ["string", "null"],
                "description": "Path to public key PEM file relative to repo root.",
            },
            "signed_payload_sha256": {
                "type": "string",
                "description": "SHA-256 of the exact byte sequence that was signed (chain tip hash as UTF-8).",
                "pattern": "^[0-9a-f]{64}$",
            },
            "signature_hex": {
                "type": "string",
                "description": "Raw signature bytes as lowercase hex.",
                "pattern": "^[0-9a-f]+$",
            },
            "signed_at_ns": {
                "type": "integer",
                "description": "Monotonic nanosecond timestamp at which signing occurred.",
            },
        },
    },

    "manifest_entry": {
        "type": "object",
        "description": "One file record in the integrity manifest.",
        "required": ["relative_path", "sha256"],
        "properties": {
            "relative_path": {"type": "string"},
            "sha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$",
            },
            "size_bytes": {"type": "integer"},
            "verified": {
                "type": "boolean",
                "description": "True if re-hashed and confirmed matching at assembly time.",
            },
            "mtime_ns": {
                "type": ["integer", "null"],
                "description": "File modification time in nanoseconds since Unix epoch.",
            },
        },
    },

    # ------------------------------------------------------------------ #
    # Suite and case records                                               #
    # ------------------------------------------------------------------ #

    "case_record": {
        "type": "object",
        "description": "Result of a single test case or script execution.",
        "required": ["name", "status", "duration_ns"],
        "properties": {
            "name":             {"type": "string"},
            "status":           {"type": "string", "enum": ["passed", "failed", "error", "skipped"]},
            "started_ns":       {"type": ["integer", "null"]},
            "ended_ns":         {"type": ["integer", "null"]},
            "duration_ns":      {"type": "integer", "description": "ended_ns - started_ns."},
            "duration_seconds": {"type": "number", "description": "duration_ns / 1e9."},
            "failure_message":  {"type": ["string", "null"]},
            "traceback":        {"type": ["string", "null"], "description": "Full traceback, capped at 8 KB."},
            "seed_used":        {"type": ["integer", "null"]},
            "stdout":           {"type": ["string", "null"], "description": "Captured stdout, capped at 4 KB."},
            "stderr_snippet":   {"type": ["string", "null"], "description": "Last 2 KB of stderr."},
            "markers":          {"type": "array", "items": {"type": "string"}},
            "parametrize_id":   {"type": ["string", "null"]},
            "dag_node_id": {
                "type": ["string", "null"],
                "description": "node_id of the corresponding node in orchestration.dag_trace.",
            },
        },
    },

    "suite_record": {
        "type": "object",
        "description": "Result block for one named suite.",
        "required": ["suite_type", "started_ns", "ended_ns", "duration_ns", "cases"],
        "properties": {
            "suite_type":       {"type": "string", "enum": ["pytest_suite", "study_script"]},
            "started_ns":       {"type": "integer"},
            "ended_ns":         {"type": "integer"},
            "duration_ns":      {"type": "integer"},
            "duration_seconds": {"type": "number"},
            "pytest_args":      {"type": ["array", "null"], "items": {"type": "string"}},
            "dag_node_id":      {"type": ["string", "null"]},
            "cases":            {"type": "array", "items": {"$ref": "#/$defs/case_record"}},
        },
    },

}


# ---------------------------------------------------------------------------
# Top-level schema document
# ---------------------------------------------------------------------------

_SCHEMA: Dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/your-repo/rgp-neural-architectures/audit/schema.json",
    "title": "RGP Audit Report",
    "description": (
        "Complete structured audit trail for one run of the RGP Neural Architectures "
        "pipeline.  Five sections: (1) immutable provenance, (2) temporal orchestration "
        "and DAG logs, (3) high-resolution mathematical telemetry, "
        "(4) hardware forensics, (5) cryptographic integrity seal."
    ),
    "type": "object",
    "additionalProperties": True,
    "required": [
        "run_id",
        "timestamp_utc",
        "provenance",
        "orchestration",
        "math_telemetry",
        "hardware_forensics",
        "suites",
        "summary",
        "integrity",
    ],

    "properties": {

        "run_id": {
            "type": "string",
            "format": "uuid",
        },

        "timestamp_utc": {
            "type": "string",
            "format": "date-time",
        },

        # ==================================================================
        # SECTION 1  Immutable Foundation
        # ==================================================================
        "provenance": {
            "type": "object",
            "description": (
                "The tamper-evident foundation.  Three immutable anchors: the exact "
                "code state (git commit hash), the deterministic key (master seed), "
                "and the cryptographic identity of every input dataset (SHA-256).  "
                "Changing any of these three means a different experiment."
            ),
            "required": ["git", "seed_registry", "data_checksums", "hardware"],
            "properties": {

                "git": {
                    "type": "object",
                    "required": ["commit_hash", "branch", "dirty"],
                    "properties": {
                        "commit_hash": {
                            "type": "string",
                            "description": "Full 40-character SHA-1 of HEAD, or 'UNKNOWN'.",
                        },
                        "branch": {
                            "type": "string",
                            "description": "Current branch name, or 'HEAD' in detached state.",
                        },
                        "dirty": {
                            "type": "boolean",
                            "description": "True when working tree contains uncommitted changes.",
                        },
                        "tags": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "remote_url": {"type": ["string", "null"]},
                        "diff_stat": {
                            "type": ["string", "null"],
                            "description": "Output of 'git diff --stat HEAD' (null when clean).",
                        },
                    },
                },

                "seed_registry": {
                    "type": "object",
                    "description": (
                        "The deterministic key.  Anyone with master_seed and a clean "
                        "checkout of the exact commit_hash can reproduce every result."
                    ),
                    "required": [
                        "master_seed", "step",
                        "deterministic_cuda", "benchmark_disabled",
                    ],
                    "properties": {
                        "master_seed": {
                            "type": "integer",
                            "minimum": 0,
                        },
                        "step": {
                            "type": "integer",
                            "minimum": 0,
                        },
                        "deterministic_cuda": {"type": "boolean"},
                        "benchmark_disabled":  {"type": "boolean"},
                        "worker_seed_formula": {
                            "type": "string",
                            "description": "Algebraic formula for per-worker seed derivation.",
                            "examples": [
                                "(master_seed * 2654435761 + worker_id * 1013904223) & 0xFFFFFFFF"
                            ],
                        },
                        "rng_snapshot_embedded": {
                            "type": "boolean",
                            "description": "True when the full Python/NumPy/Torch RNG state is in the first checkpoint.",
                        },
                    },
                },

                "data_checksums": {
                    "type": "array",
                    "description": (
                        "SHA-256 checksums of every input dataset used in this run, "
                        "generated by DataAuditor.compute_checksum() before training."
                    ),
                    "items": {"$ref": "#/$defs/data_identity"},
                },

                "hardware": {
                    "type": "object",
                    "description": "Static hardware profile captured at run start.",
                    "required": [
                        "device_type", "device_name",
                        "python_version", "torch_version",
                    ],
                    "properties": {
                        "device_type":           {"type": "string", "enum": ["cuda", "mps", "cpu"]},
                        "device_name":           {"type": "string"},
                        "cuda_version":          {"type": ["string", "null"]},
                        "total_memory_gb":       {"type": ["number", "null"]},
                        "multi_processor_count": {"type": ["integer", "null"]},
                        "compute_capability":    {"type": ["string", "null"]},
                        "cudnn_version":         {"type": ["string", "null"]},
                        "cpu_count":             {"type": "integer"},
                        "cpu_model":             {"type": "string"},
                        "platform":              {"type": "string"},
                        "python_version":        {"type": "string"},
                        "torch_version":         {"type": "string"},
                        "numpy_version":         {"type": "string"},
                    },
                },

            },
        },

        # ==================================================================
        # SECTION 2  Temporal & Orchestration Logs
        # ==================================================================
        "orchestration": {
            "type": "object",
            "description": (
                "Complete temporal record of the workflow.  Every major execution "
                "unit emits a DAG node with nanosecond-resolution timestamps.  "
                "Checkpoint interrupt and recovery events are recorded so the "
                "audit trail is unbroken across multi-day runs with restarts."
            ),
            "required": ["wall_start_ns", "dag_trace"],
            "properties": {

                "wall_start_ns": {
                    "type": "integer",
                    "description": "time.monotonic_ns() at run start.",
                },
                "wall_end_ns": {
                    "type": ["integer", "null"],
                    "description": "time.monotonic_ns() at run end.",
                },
                "wall_duration_seconds": {
                    "type": ["number", "null"],
                },

                "dag_trace": {
                    "type": "array",
                    "description": (
                        "Ordered execution trace of all DAG nodes, appended in completion "
                        "order.  Reconstruct the full DAG by grouping on parent_node_id."
                    ),
                    "items": {"$ref": "#/$defs/dag_node"},
                },

                "checkpoint_events": {
                    "type": "array",
                    "description": "Complete log of saves, interruptions, and resumptions.  Empty array for clean runs.",
                    "items": {"$ref": "#/$defs/checkpoint_event"},
                },

                "total_interruptions": {"type": "integer"},
                "total_resumptions":   {"type": "integer"},

            },
        },

        # ==================================================================
        # SECTION 3  High-Resolution Mathematical Telemetry
        # ==================================================================
        "math_telemetry": {
            "type": "object",
            "description": (
                "The scientific core of the audit.  Four time series indexed by "
                "training step, enabling reviewers to inspect the full trajectory "
                "of every quantity.  Sampling frequency for each series is declared "
                "in telemetry_sampling_config."
            ),
            "required": [
                "spectral_map",
                "lyapunov_evolution",
                "fisher_geometry",
                "rg_operator_flow",
            ],
            "properties": {

                "spectral_map": {
                    "type": "array",
                    "description": (
                        "Layer-wise singular value spectra.  Each snapshot records the "
                        "complete SVD of one layer's weight matrix at one step.  The full "
                        "distribution (not just mean or max) is required for Marchenko-Pastur "
                        "fitting, effective-rank tracking, and Tracy-Widom edge detection."
                    ),
                    "items": {"$ref": "#/$defs/spectral_snapshot"},
                },

                "lyapunov_evolution": {
                    "type": "array",
                    "description": (
                        "Full Lyapunov spectrum sampled throughout training.  "
                        "max_lyapunov_exponent vs step reveals the ordered-to-chaotic "
                        "phase transition; kaplan_yorke_dimension vs depth gives the "
                        "fractal dimension of the learned representation."
                    ),
                    "items": {"$ref": "#/$defs/lyapunov_snapshot"},
                },

                "fisher_geometry": {
                    "type": "array",
                    "description": (
                        "Fisher metric geometry sampled at each layer and step.  "
                        "condition_number drives H1 validation; effective_dimension "
                        "drives the minimal-depth argument in H2."
                    ),
                    "items": {"$ref": "#/$defs/fisher_snapshot"},
                },

                "rg_operator_flow": {
                    "type": "array",
                    "description": (
                        "RG information flow coefficients.  The cumulative_information_loss "
                        "trajectory across depth is the primary mathematical evidence that "
                        "depth functions as the coarse-graining scale (H1 core claim)."
                    ),
                    "items": {"$ref": "#/$defs/rg_operator_snapshot"},
                },

                "telemetry_sampling_config": {
                    "type": "object",
                    "description": "Step intervals at which each telemetry type was sampled.",
                    "properties": {
                        "spectral_every_n_steps":  {"type": "integer"},
                        "lyapunov_every_n_steps":  {"type": "integer"},
                        "fisher_every_n_steps":    {"type": "integer"},
                        "rg_flow_every_n_steps":   {"type": "integer"},
                        "total_steps_in_run":      {"type": ["integer", "null"]},
                    },
                },

            },
        },

        # ==================================================================
        # SECTION 4  Hardware Forensics
        # ==================================================================
        "hardware_forensics": {
            "type": "object",
            "description": (
                "Dynamic hardware measurements collected during execution.  "
                "The VRAM micro-log and kernel latency records are the empirical "
                "evidence for the O(N) complexity claim.  Plotting cumulative_bytes "
                "vs layer_idx must be linear; plotting kernel duration_us vs "
                "problem_size_n must be linear."
            ),
            "required": ["vram_micro_log", "kernel_latency_log"],
            "properties": {

                "vram_micro_log": {
                    "type": "array",
                    "description": (
                        "Per-event GPU memory allocation log.  Captured at every "
                        "layer materialisation and tensor move-to-device call.  "
                        "Each entry records exact byte delta and cumulative total."
                    ),
                    "items": {"$ref": "#/$defs/vram_alloc_event"},
                },

                "kernel_latency_log": {
                    "type": "array",
                    "description": (
                        "Per-kernel GPU compute latency.  Measured via torch.cuda.Event "
                        "start/stop pairs around forward and backward passes."
                    ),
                    "items": {"$ref": "#/$defs/kernel_latency_record"},
                },

                "peak_vram_bytes": {
                    "type": ["integer", "null"],
                    "description": "Maximum cumulative_bytes observed during the run.",
                },
                "peak_vram_gb": {"type": ["number", "null"]},
                "total_kernel_time_seconds": {
                    "type": ["number", "null"],
                    "description": "Sum of all kernel_latency_log duration_us values, in seconds.",
                },

            },
        },

        # ==================================================================
        # Test / study suites
        # ==================================================================
        "suites": {
            "type": "object",
            "description": "Map of suite_name -> suite result block.",
            "additionalProperties": {"$ref": "#/$defs/suite_record"},
        },

        "summary": {
            "type": "object",
            "required": [
                "total_cases", "passed", "failed", "errored",
                "skipped", "duration_seconds", "all_passed",
            ],
            "properties": {
                "total_cases":      {"type": "integer"},
                "passed":           {"type": "integer"},
                "failed":           {"type": "integer"},
                "errored":          {"type": "integer"},
                "skipped":          {"type": "integer"},
                "duration_seconds": {"type": "number"},
                "all_passed":       {"type": "boolean"},
                "suite_summary": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": ["passed", "failed", "errored", "skipped"],
                        "properties": {
                            "passed":  {"type": "integer"},
                            "failed":  {"type": "integer"},
                            "errored": {"type": "integer"},
                            "skipped": {"type": "integer"},
                        },
                    },
                },
            },
        },

        # ==================================================================
        # SECTION 5  Cryptographic Integrity Seal
        # ==================================================================
        "integrity": {
            "type": "object",
            "description": (
                "Cryptographic seal making the report tamper-evident.  The hash chain "
                "links every section to all preceding sections.  Modifying a single "
                "value in section 1 changes that block's sha256, cascades through every "
                "subsequent chain_hash, and breaks signature verification at the tip.  "
                "The manifest records SHA-256 of every repository file at assembly time."
            ),
            "required": ["hash_chain", "chain_root_hash", "chain_tip_hash"],
            "properties": {

                "hash_chain": {
                    "type": "array",
                    "description": (
                        "Ordered chain of block hash records.  Genesis block (index 0) "
                        "hashes provenance.  Subsequent blocks hash orchestration, "
                        "math_telemetry, hardware_forensics, suites, summary  in that "
                        "order.  Minimum 6 blocks required."
                    ),
                    "items": {"$ref": "#/$defs/block_hash_record"},
                    "minItems": 6,
                },

                "chain_root_hash": {
                    "type": "string",
                    "description": "chain_hash of the genesis block (block_index == 0).",
                    "pattern": "^[0-9a-f]{64}$",
                },

                "chain_tip_hash": {
                    "type": "string",
                    "description": "chain_hash of the final block.  This is the value that is signed.",
                    "pattern": "^[0-9a-f]{64}$",
                },

                "signature": {
                    "oneOf": [
                        {"$ref": "#/$defs/digital_signature"},
                        {"type": "null"},
                    ],
                    "description": (
                        "Digital signature over chain_tip_hash.  Null for development runs; "
                        "required for archival and submission runs."
                    ),
                },

                "manifest": {
                    "type": "object",
                    "description": "Integrity manifest of repository files at assembly time.",
                    "properties": {
                        "entries": {
                            "type": "array",
                            "items": {"$ref": "#/$defs/manifest_entry"},
                        },
                        "manifest_hash": {
                            "type": "string",
                            "description": "SHA-256 of the JSON-serialised entries array.",
                            "pattern": "^[0-9a-f]{64}$",
                        },
                        "verified_at_ns": {"type": "integer"},
                        "total_files":   {"type": "integer"},
                        "total_bytes":   {"type": "integer"},
                    },
                },

                "schema_warnings": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Validation errors from AuditSchema.validate_soft() at assembly time.",
                },

            },
        },

    },  # /properties

    "$defs": _DEFS,
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class AuditSchema:
    """
    Wrapper around the raw JSON Schema document.

    Provides schema access, JSON serialisation, and jsonschema-backed
    validation in both raising and non-raising forms.
    """

    RAW: Dict[str, Any] = _SCHEMA

    @classmethod
    def as_json(cls, indent: int = 2) -> str:
        return json.dumps(cls.RAW, indent=indent, ensure_ascii=False)

    @classmethod
    def validate(cls, instance: Dict[str, Any]) -> None:
        """
        Validate *instance* against the schema.

        Raises jsonschema.ValidationError on failure, ImportError if
        jsonschema is not installed.
        """
        try:
            import jsonschema
        except ImportError as exc:
            raise ImportError(
                "Install 'jsonschema' to enable strict schema validation: "
                "pip install jsonschema"
            ) from exc
        jsonschema.validate(instance=instance, schema=cls.RAW)

    @classmethod
    def validate_soft(cls, instance: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """
        Non-raising validation.

        Returns (True, []) on success; (False, [error_strings]) on failure;
        (True, ["jsonschema not installed..."]) when jsonschema is absent.
        """
        try:
            import jsonschema
            validator = jsonschema.Draft202012Validator(cls.RAW)
            errors    = sorted(validator.iter_errors(instance), key=lambda e: e.path)
            if errors:
                msgs = [
                    f"{'.'.join(str(p) for p in e.absolute_path)}: {e.message}"
                    for e in errors
                ]
                return False, msgs
            return True, []
        except ImportError:
            return True, ["jsonschema not installed; schema validation skipped"]
