
defaults:
  - override

_override_:
  analysis:
    correlation_length:
      n_layers_to_analyze: 10
      estimators: [exponential_decay]
    widths: [64, 128]
    n_seeds: 3
    fisher_mc_samples: 100
    bootstrap_n_resamples: 100

